# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ipyvasp',
                'doc_host': 'https://massgh.github.io',
                'git_url': 'https://github.com/massgh/ipyvasp',
                'lib_path': 'ipyvasp'},
  'syms': {'ipyvasp\\core': {'ipyvasp\\core.foo': ('core.html#foo', 'ipyvasp\\core.py')}}}