name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/source/**"
      - "docs/Makefile"
      - "docs/requirements.txt"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install sphinx
          pip install -r docs/requirements.txt || true

      - name: Build HTML
        run: |
          cd docs
          make html
          touch build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html